// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscribe.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message keyword will generate a struct in golang
// Changed to uint 64 and compiled
type SubscribeMessage struct {
	RefreshRate          uint64   `protobuf:"varint,1,opt,name=refreshRate,proto3" json:"refreshRate,omitempty"`
	StatisticsType       string   `protobuf:"bytes,2,opt,name=statisticsType,proto3" json:"statisticsType,omitempty"`
	SMAChannel           string   `protobuf:"bytes,3,opt,name=SMAChannel,proto3" json:"SMAChannel,omitempty"`
	SMALength            uint64   `protobuf:"varint,4,opt,name=SMALength,proto3" json:"SMALength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeMessage) Reset()         { *m = SubscribeMessage{} }
func (m *SubscribeMessage) String() string { return proto.CompactTextString(m) }
func (*SubscribeMessage) ProtoMessage()    {}
func (*SubscribeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d2980c9543da44, []int{0}
}

func (m *SubscribeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeMessage.Unmarshal(m, b)
}
func (m *SubscribeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeMessage.Marshal(b, m, deterministic)
}
func (m *SubscribeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeMessage.Merge(m, src)
}
func (m *SubscribeMessage) XXX_Size() int {
	return xxx_messageInfo_SubscribeMessage.Size(m)
}
func (m *SubscribeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeMessage proto.InternalMessageInfo

func (m *SubscribeMessage) GetRefreshRate() uint64 {
	if m != nil {
		return m.RefreshRate
	}
	return 0
}

func (m *SubscribeMessage) GetStatisticsType() string {
	if m != nil {
		return m.StatisticsType
	}
	return ""
}

func (m *SubscribeMessage) GetSMAChannel() string {
	if m != nil {
		return m.SMAChannel
	}
	return ""
}

func (m *SubscribeMessage) GetSMALength() uint64 {
	if m != nil {
		return m.SMALength
	}
	return 0
}

type NotificationMessage struct {
	Top10                string   `protobuf:"bytes,1,opt,name=top10,proto3" json:"top10,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationMessage) Reset()         { *m = NotificationMessage{} }
func (m *NotificationMessage) String() string { return proto.CompactTextString(m) }
func (*NotificationMessage) ProtoMessage()    {}
func (*NotificationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d2980c9543da44, []int{1}
}

func (m *NotificationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationMessage.Unmarshal(m, b)
}
func (m *NotificationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationMessage.Marshal(b, m, deterministic)
}
func (m *NotificationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationMessage.Merge(m, src)
}
func (m *NotificationMessage) XXX_Size() int {
	return xxx_messageInfo_NotificationMessage.Size(m)
}
func (m *NotificationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationMessage proto.InternalMessageInfo

func (m *NotificationMessage) GetTop10() string {
	if m != nil {
		return m.Top10
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeMessage)(nil), "proto.SubscribeMessage")
	proto.RegisterType((*NotificationMessage)(nil), "proto.NotificationMessage")
}

func init() { proto.RegisterFile("subscribe.proto", fileDescriptor_38d2980c9543da44) }

var fileDescriptor_38d2980c9543da44 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x4d, 0x2a,
	0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a,
	0xb3, 0x18, 0xb9, 0x04, 0x82, 0x61, 0x52, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x0a,
	0x5c, 0xdc, 0x45, 0xa9, 0x69, 0x45, 0xa9, 0xc5, 0x19, 0x41, 0x89, 0x25, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x2c, 0x41, 0xc8, 0x42, 0x42, 0x6a, 0x5c, 0x7c, 0xc5, 0x25, 0x89, 0x25, 0x99, 0xc5,
	0x25, 0x99, 0xc9, 0xc5, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x68,
	0xa2, 0x42, 0x72, 0x5c, 0x5c, 0xc1, 0xbe, 0x8e, 0xce, 0x19, 0x89, 0x79, 0x79, 0xa9, 0x39, 0x12,
	0xcc, 0x60, 0x35, 0x48, 0x22, 0x42, 0x32, 0x5c, 0x9c, 0xc1, 0xbe, 0x8e, 0x3e, 0xa9, 0x79, 0xe9,
	0x25, 0x19, 0x12, 0x2c, 0x60, 0x7b, 0x10, 0x02, 0x4a, 0xda, 0x5c, 0xc2, 0x7e, 0xf9, 0x25, 0x99,
	0x69, 0x99, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x30, 0xe7, 0x89, 0x70, 0xb1, 0x96, 0xe4, 0x17,
	0x18, 0x1a, 0x80, 0x1d, 0xc6, 0x19, 0x04, 0xe1, 0x18, 0x85, 0x71, 0xf1, 0x40, 0x3d, 0x52, 0x00,
	0x52, 0x2c, 0xe4, 0xc6, 0xc5, 0x09, 0xf7, 0x98, 0x90, 0x38, 0xc4, 0xd7, 0x7a, 0xe8, 0x5e, 0x95,
	0x92, 0x82, 0x4a, 0x60, 0xb1, 0x47, 0x89, 0x41, 0x83, 0xd1, 0x80, 0x31, 0x89, 0x0d, 0xac, 0xc0,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x1d, 0x25, 0xb4, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubscriptionClient is the client API for Subscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscriptionClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Subscription_SubscribeClient, error)
}

type subscriptionClient struct {
	cc *grpc.ClientConn
}

func NewSubscriptionClient(cc *grpc.ClientConn) SubscriptionClient {
	return &subscriptionClient{cc}
}

func (c *subscriptionClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Subscription_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Subscription_serviceDesc.Streams[0], "/proto.Subscription/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionSubscribeClient{stream}
	return x, nil
}

type Subscription_SubscribeClient interface {
	Send(*SubscribeMessage) error
	Recv() (*NotificationMessage, error)
	grpc.ClientStream
}

type subscriptionSubscribeClient struct {
	grpc.ClientStream
}

func (x *subscriptionSubscribeClient) Send(m *SubscribeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *subscriptionSubscribeClient) Recv() (*NotificationMessage, error) {
	m := new(NotificationMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriptionServer is the server API for Subscription service.
type SubscriptionServer interface {
	Subscribe(Subscription_SubscribeServer) error
}

func RegisterSubscriptionServer(s *grpc.Server, srv SubscriptionServer) {
	s.RegisterService(&_Subscription_serviceDesc, srv)
}

func _Subscription_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SubscriptionServer).Subscribe(&subscriptionSubscribeServer{stream})
}

type Subscription_SubscribeServer interface {
	Send(*NotificationMessage) error
	Recv() (*SubscribeMessage, error)
	grpc.ServerStream
}

type subscriptionSubscribeServer struct {
	grpc.ServerStream
}

func (x *subscriptionSubscribeServer) Send(m *NotificationMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *subscriptionSubscribeServer) Recv() (*SubscribeMessage, error) {
	m := new(SubscribeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Subscription_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Subscription",
	HandlerType: (*SubscriptionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Subscription_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "subscribe.proto",
}
